# site settings
title: Avril M. Harder
subtitle: Research
email: 
description: PhD candidate in the Christie lab at Purdue University. Interested in evolution and fishes.
baseurl:  "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Avril Harder
street_address: 915 W. State St.
city: West Lafayette
state: IN
zip_code: 47907
country: United States of America
phone: 

# social settings
500px_url:
github_url: https://github.com/avril-m-harder
instagram_url: https://www.instagram.com/avrilmaellen/
linkedin_url: 
slack_url:
twitter_url: https://twitter.com/avrilmharder

# build settings
markdown: kramdown

sass:
  style: compressed
