# site settings
title: Avril M. Harder
subtitle: - Research
email: 
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/research" # the subpath of your site, e.g. /blog
url: "https://avril-m-harder.github.io" # the base hostname & protocol for your site
author: Avril Harder
street_address: 915 W. State St.
city: West Lafayette
state: IN
zip_code: 47907
country: United States of America
phone: 

# social settings
500px_url:
facebook_url:
github_url: https://github.com/andrewbanchich
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
