# site settings
title: Avril M. Harder
subtitle: Evolutionary genomics
email: avrilharder [at] gmail [dot] com
description: NSF Postdoctoral Fellow&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br /><br />Evolution |  Conservation | Genomics 
baseurl: # the subpath of your site, e.g. /blog
url: "https://avril-m-harder.github.io" # the base hostname & protocol for your site
author:
street_address: Forestry and Wildlife Sciences Bldg.<br />602 Duncan Dr.
city: Auburn
state: AL
zip_code: 36849
country: United States of America
phone: (773) 688-8564

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url: https://github.com/avril-m-harder
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/avrilmaellen
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/avrilmharder

# build settings
markdown: kramdown

sass:
  style: compressed

# Google tracking
google_analytics: UA—105246308-2
