# site settings
title: Avril M. Harder
subtitle: Salmonid genomics
email: avrilharder@gmail.com
description: PhD candidate in the Christie lab at Purdue University<br />Evolution | Gene expression | Fishes
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 915 W. State St.
city: West Lafayette
state: IN
zip_code: 47907
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/avril-m-harder
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/avrilmaellen
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/avrilmharder

# build settings
markdown: kramdown

sass:
  style: compressed
